const TasksActionTypes = {
  FETCH_TASKS_START: "FETCH_TASKS_START",
  FETCH_TASKS_SUCESS: "FETCH_TASKS_SUCESS",
  FETCH_TASKS_FAILURE: "FETCH_TASKS_FAILURE",
  POST_TASK_START: "POST_TASK_START",
  POST_TASK_SUCESS: "POST_TASK_SUCESS",
  POST_TASK_FAILURE: "POST_TASK_FAILURE",
  DELETE_TASK_START: "DELETE_TASK_START",
  DELETE_TASK_SUCESS: "DELETE_TASK_SUCESS",
  DELETE_TASK_FAILURE: "DELETE_TASK_FAILURE",
  UPDATE_TASK_START: "UPDATE_TASK_START",
  UPDATE_TASK_SUCESS: "UPDATE_TASK_SUCESS",
  UPDATE_TASK_FAILURE: "UPDATE_TASK_FAILURE",
};

export default TasksActionTypes;
