const UserActionTypes = {
  GOOGLE_SIGNIN_START: "GOOGLE_SIGNIN_START",
  SIGNIN_FAILURE: "SIGNIN_FAILURE",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  EMAIL_SIGNIN_START: "EMAIL_SIGNIN_START",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
  GET_AVATAR_START: "GET_AVATAR_START",
  GET_AVATAR_SUCCESS: "GET_AVATAR_SUCCESS",
  GET_AVATAR_FAILURE: "GET_AVATAR_FAILURE",
  UPDATE_USER_START: "UPDATE_USER_START",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",
};

export default UserActionTypes;
